#Pollution Plot 5 -Baltimore motor vehicle emissions
library("ggplot2")
baltimore <- filter(NEI, fips=="24510")
motorNames <- filter(SCC, grepl(".*Motor.*",Short.Name))
motorNames2 <- filter(SCC, Data.Category == "Onroad")
mbaltimore <- merge(baltimore, motorNames2, by = "SCC")
summary5 <- summarise(group_by(mbaltimore,year), Emissions = sum(Emissions))
plot5 <- ggplot(summary5, aes(year, Emissions))
#png("plot5.png", width=580, height=580, units="px", pointsize = 8, type = "quartz")
plot5 + geom_point(color = c("red","blue","blue","red"),size=6) + geom_smooth(method="lm", se=FALSE) +labs(title = "Baltimore City On-Road Emissions (in tons) 1999-2008 \n Showing Decreases Over Time")
#dev.off()
